version: '3.8'

services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp:latest
    container_name: nginx-rtmp
    ports:
      - "1935:1935"  # RTMP port
      - "8080:8080"  # HLS port
      - "8081:8081"  # Admin port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - hls_data:/tmp/hls
      - recordings_data:/tmp/recordings
      - logs_data:/var/log/nginx
    restart: unless-stopped
    networks:
      - rtmp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  rtmp-controller:
    build: .
    container_name: rtmp-controller
    ports:
      - "3000:3000"  # Web interface port
    depends_on:
      nginx-rtmp:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=3000
      - RTMP_INPUT_URL=rtmp://nginx-rtmp:1935/live/stream
    volumes:
      - logs_data:/app/logs
    restart: unless-stopped
    networks:
      - rtmp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  rtmp-network:
    driver: bridge

volumes:
  hls_data:
  recordings_data:
  logs_data: